name: Auto Merge PR

on: 
  pull_request:
    types: [opened, reopened]

env:
  FILE_NAME: hello-server

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: flake8 and pylint
        run: |
          pip install -r requirements.txt
          flake8 --ignore=E501,E231 *.py tests/*.py
          pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py

      - name: unit test
        run: python -m unittest --verbose --failfast

  merge:
    if: github.actor == 'alex-valchuk' || github.actor == 'octocat'
    needs: lint
    runs-on: ubuntu-latest
    environment: github-actions-training

    steps:

      - run: git config --global --add safe.directory /github/workspace
      
      - uses: actions/checkout@v1

      - uses: hmarr/auto-approve-action@v2.0.0
        with:
           github-token: ${{ secrets.MY_GITHUB_TOKEN }}
      
      - uses: managedkaos/merge-pull-request@v1.2
        env:
           GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
