name: Challenge CI/CD

env:
  APPLICATION_NAME: app2

on: push

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python Environment
      uses: actions/setup-python@v3
      
    - name: Run script
      run: python hello.py

  build:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
    - uses: actions/checkout@v2

    - uses: actions/upload-artifact@v1.0.0
      with: 
        name: linux
        path: .

