name: Challenge Artifacts

env:
  ARTIFACT_NAME: 'Some Artifact'
  FILE_NAME: 'hello-server.go'

on: push

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Upload artifact for linux
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./${{ env.FILE_NAME }}
